# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.1'

services:
  catalog:
    image: catalog:v1
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:80
    depends_on:
      - mongodb
    environment:
      - MongoDbSettings:Host=mongodb
      - MongoDbSettings:Password=Password123
      - ASPNETCORE_URLS=http://+:80

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Password123
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
